# @package _group_

name: ffhq_${dataset.resolution}_aligned
sampling:
  fov: 12.0
  ray_start: 0.88
  ray_end: 1.12
  radius: 1.0
  dist: custom
  # dist: gaussian
  # horizontal_stddev: 0.3
  # horizontal_mean: 3.141592653589793
  # vertical_mean: 1.57079632679
  # vertical_stddev: 0.15
cube_scale: 0.2
white_back: false
last_back: false
