# @package _group_

# Checkpoint loading options
ckpt:
  network_pkl: ~ # Network pickle filename
  networks_dir: ~ # Network pickles directory
  selection_metric: fid2k_full # Which metric to use when selecting the best ckpt?
  reload_code: false

metrics: "fid50k_full" # Comma-separated list of metric names
data: ~ # Path to the dataset to evaluate metrics against (directory or zip)
mirror: ~ # Whether the dataset was augmented with x-flips during training. Default: look up
gpus: 1 # Number of GPUs to use
img_resolution: 256 # Image resolution of the generator?
verbose: false
